### ISSUE TITLE
Consider adding health checks for operator's kube-rbac-proxy container

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#359] opened 2024-05-14 09:03 UTC
Add liveness/readiness probes to kube-rbac-proxy container

**Comment by nickboldt** [comment] 2024-07-29 21:48
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-2321

... which was closed as a dupe of something.

**Closed by nickboldt** 2024-07-29 21:48 UTC
Labels: good first issue, priority/low, kind/task, jira
